name: Deploy to DigitalOcean

on:
  workflow_dispatch:

env: 
  CONTAINER_NAME: git-registry
  IMAGE_NAME: github-workflows

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      # run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      # run: docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/$(echo $IMAGE_NAME)
      run: docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/$(echo $IMAGE_NAME)
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/$(echo $IMAGE_NAME)
      
    # - name: Install doctl
    #   uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{ secrets.DOCTL_SECRET }}
        
    # - name: Log in to DigitalOcean Container Registry with short-lived credentials
    #   run: doctl registry login --expiry-seconds 600

    # - name: Push image to Docker hub
    #   run: docker push aoffis/github-workflows:${{ github.sha }}
