name: Deploy to DigitalOcean

on:
  workflow_dispatch:
env: 
  CONTAINER_NAME: git-registry
  IMAGE_NAME: deploy-image
  USERNAME: ${{ secrets.USER }}
  TOKEN: ${{ secrets.TOKEN }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: docker login    
      # run: echo ${{ vars.TOKEN }} | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin
      run: echo ${{ secrets.TOKEN }} | docker login -u ${{ secrets.USERNAME }} --password-stdin
    # - name: Build container image
    #   run: docker build -t registry.digitalocean.com/$CONTAINER_NAME/$IMAGE_NAME:${{ github.sha }} .
   
    # - name: Install doctl
    #   uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{ secrets.DOCTL_SECRET }}
        
    # - name: Log in to DigitalOcean Container Registry with short-lived credentials
    #   run: doctl registry login --expiry-seconds 600

    # - name: Push image to Docker hub
    #   run: docker push aoffis/github-workflows:${{ github.sha }}
