name: Deploy to DigitalOcean

on:
  workflow_dispatch:

env: 
  CONTAINER_NAME: git-registry
  IMAGE_NAME: deploy-image

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ secrets.USER }} --password-stdin
   
    # - name: Install doctl
    #   uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{ secrets.DOCTL_SECRET }}
        
    # - name: Log in to DigitalOcean Container Registry with short-lived credentials
    #   run: doctl registry login --expiry-seconds 600

    # - name: Push image to Docker hub
    #   run: docker push aoffis/github-workflows:${{ github.sha }}
