name: Deploy to DigitalOcean

on:
  workflow_dispatch:
env: 
  CONTAINER_NAME: git-registry
  IMAGE_NAME: deploy-image
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build container image
      run: docker build -t registry.digitalocean.com/$CONTAINER_NAME/$IMAGE_NAME:${{ github.sha }} .
