name: Deploy to DigitalOcean

on:
  workflow_dispatch:
env: 
  CONTAINER_NAME: git-registry
  IMAGE_NAME: deplot-image
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta

    - name: Build container image
      run: docker build -t registry.digitalocean.com/$CONTAINER_NAME/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7) .
